"""Typed domain objects used across research, portfolio, and backtesting layers."""

from .models import (
    DataProvenance,
    MetricObservation,
    MetricStatus,
    Period,
    Score,
    ScoreComponent,
    Ticker,
)
from .market import (
    CorporateAction,
    DividendAction,
    PriceAdjustmentPolicy,
    PriceBar,
    Quote,
    SplitAction,
    SpinoffAction,
)
from .research import ResearchResult, ResearchRun, ResearchRunStatus
from .research_engine import (
    AnalysisStatus,
    CompositeScore,
    CriterionResult,
    CriterionStatus,
    FactorObservation,
    FactorScore,
    MissingDataPolicy,
    PointInTimeDataView,
    ResearchOutcome,
    UniverseLimitation,
    UniverseSnapshot,
)
from .research_intelligence import (
    ChangeType, CohortIdentity, DriverDirection, FactorEfficacySummary,
    FactorOutcomeObservation, MaterialityPolicy, MaterialityRule, MaterialityRuleType,
    MonitoringEvent, ReportSection, ResearchChangeEvent, ResearchReport,
    SourceReference, StrategyComparison, ThesisAssumption, ThesisClassification,
    ThesisDriver, ThesisDriverCategory, ThesisInvalidator, ThesisSnapshot,
    WatchCondition, WatchlistEntry, WatchlistStatus,
)
from .statistical_validation import (
    BootstrapMethod, ConfidenceInterval, CrossSectionalICObservation, DataPartition,
    DateWindow, FactorValidationSummary, HypothesisTestResult, MultipleTestingMethod,
    SamplingMethod, StatisticalDatasetManifest, StatisticalStatus,
    StatisticalValidationRun, ValidationCohort, WalkForwardWindow,
)
from .filings import (
    ClaimCategory,
    ClaimDirection,
    ClaimMethod,
    ClaimStatus,
    FilingChangeType,
    FilingDocument,
    FilingEvidenceReference,
    FilingEvidenceSnapshot,
    FilingForm,
    FilingSection,
    FilingSectionChange,
    FilingSectionKind,
    QualitativeClaim,
)
from .automation import (
    AutomationFailureKind,
    AutomationRun,
    AutomationRunStatus,
    AutomationStepName,
    AutomationStepResult,
    AutomationStepStatus,
    AutomationTrigger,
    AutomationTriggerKind,
    ResearchAutomationDefinition,
    RetryPolicy,
)
from .portfolio_construction import (
    ConstraintEvaluation,
    ConstraintStatus,
    ConstructionStatus,
    CurrentPortfolioWeight,
    PortfolioConstraint,
    PortfolioConstraintKind,
    PortfolioConstructionPolicy,
    PortfolioConstructionRequest,
    PortfolioConstructionResult,
    TargetPosition,
    TradeEstimate,
    WeightingMethod,
)
from .interactive import (
    OutcomeVisibility,
    ResearchView,
    ResearchViewKind,
    ResearchViewLink,
    ResearchViewRequest,
    ResearchViewStatus,
)
from .narrative import NarrativePolicy, NarrativeRequest, NarrativeResult, NarrativeStatus

__all__ = [
    "DataProvenance",
    "MetricObservation",
    "MetricStatus",
    "Period",
    "Score",
    "ScoreComponent",
    "Ticker",
    "CorporateAction",
    "DividendAction",
    "PriceAdjustmentPolicy",
    "PriceBar",
    "Quote",
    "ResearchResult",
    "ResearchRun",
    "ResearchRunStatus",
    "SplitAction",
    "SpinoffAction",
    "AnalysisStatus",
    "CompositeScore",
    "CriterionResult",
    "CriterionStatus",
    "FactorObservation",
    "FactorScore",
    "MissingDataPolicy",
    "PointInTimeDataView",
    "ResearchOutcome",
    "UniverseLimitation",
    "UniverseSnapshot",
    "ChangeType",
    "CohortIdentity",
    "DriverDirection",
    "FactorEfficacySummary",
    "FactorOutcomeObservation",
    "MaterialityPolicy",
    "MaterialityRule",
    "MaterialityRuleType",
    "MonitoringEvent",
    "ReportSection",
    "ResearchChangeEvent",
    "ResearchReport",
    "SourceReference",
    "StrategyComparison",
    "ThesisAssumption",
    "ThesisClassification",
    "ThesisDriver",
    "ThesisDriverCategory",
    "ThesisInvalidator",
    "ThesisSnapshot",
    "WatchCondition",
    "WatchlistEntry",
    "WatchlistStatus",
    "BootstrapMethod",
    "ConfidenceInterval",
    "CrossSectionalICObservation",
    "DataPartition",
    "DateWindow",
    "FactorValidationSummary",
    "HypothesisTestResult",
    "MultipleTestingMethod",
    "SamplingMethod",
    "StatisticalDatasetManifest",
    "StatisticalStatus",
    "StatisticalValidationRun",
    "ValidationCohort",
    "WalkForwardWindow",
    "ClaimCategory",
    "ClaimDirection",
    "ClaimMethod",
    "ClaimStatus",
    "FilingChangeType",
    "FilingDocument",
    "FilingEvidenceReference",
    "FilingEvidenceSnapshot",
    "FilingForm",
    "FilingSection",
    "FilingSectionChange",
    "FilingSectionKind",
    "QualitativeClaim",
    "AutomationFailureKind",
    "AutomationRun",
    "AutomationRunStatus",
    "AutomationStepName",
    "AutomationStepResult",
    "AutomationStepStatus",
    "AutomationTrigger",
    "AutomationTriggerKind",
    "ResearchAutomationDefinition",
    "RetryPolicy",
    "ConstraintEvaluation",
    "ConstraintStatus",
    "ConstructionStatus",
    "CurrentPortfolioWeight",
    "PortfolioConstraint",
    "PortfolioConstraintKind",
    "PortfolioConstructionPolicy",
    "PortfolioConstructionRequest",
    "PortfolioConstructionResult",
    "TargetPosition",
    "TradeEstimate",
    "WeightingMethod",
    "OutcomeVisibility",
    "ResearchView",
    "ResearchViewKind",
    "ResearchViewLink",
    "ResearchViewRequest",
    "ResearchViewStatus",
    "NarrativePolicy",
    "NarrativeRequest",
    "NarrativeResult",
    "NarrativeStatus",
]
